import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const ROOT_DIR = process.cwd();
const OUT_DIR = path.join(ROOT_DIR, "docs", "backlog");
const ISSUES_DIR = path.join(OUT_DIR, "issues");
const WIKI_DIR = path.join(OUT_DIR, "wiki");

let config;
let baseUrl;

async function main() {
  const [command, issueKey] = process.argv.slice(2);

  if (!["sync", "task"].includes(command)) {
    throw new Error("コマンドは sync または task を指定してください。");
  }

  if (command === "task" && !issueKey) {
    throw new Error("課題キーを指定してください: npm run backlog:task -- PROJECT-123");
  }

  await loadEnv();
  config = readConfig();
  baseUrl = `https://${config.spaceId}.${config.domain}/api/v2`;

  if (command === "sync") {
    await syncBacklog();
    return;
  }

  if (command === "task") {
    await writeCurrentTask(issueKey);
    return;
  }
}

function readConfig() {
  const maxIssues = parseInt(process.env.BACKLOG_MAX_ISSUES || "100", 10);

  return {
    spaceId: requiredEnv("BACKLOG_SPACE_ID"),
    apiKey: requiredEnv("BACKLOG_API_KEY"),
    projectKey: requiredEnv("BACKLOG_PROJECT_KEY"),
    domain: process.env.BACKLOG_DOMAIN || "backlog.com",
    maxIssues: Number.isFinite(maxIssues) && maxIssues > 0 ? maxIssues : 100,
    redactPersonalInfo: process.env.BACKLOG_REDACT_PERSONAL_INFO !== "false",
  };
}

async function syncBacklog() {
  await ensureOutputDirs();

  const project = await apiGet(`/projects/${encodeURIComponent(config.projectKey)}`);
  const issues = await fetchIssues(project.id);
  console.log(`[backlog] ${issues.length}件の課題を取得しました。`);

  const issueRows = [];
  for (const issue of issues) {
    const comments = await fetchComments(issue.issueKey);
    const markdown = renderIssueMarkdown(issue, comments);
    const fileName = `${safeFileName(issue.issueKey)}.md`;
    await writeFile(path.join(ISSUES_DIR, fileName), markdown, "utf8");
    issueRows.push(`- [${issue.issueKey}](./issues/${fileName}) ${safeText(issue.summary)}`);
  }

  await writeFile(path.join(OUT_DIR, "issues.md"), [`# Backlog Issues`, "", ...issueRows, ""].join("\n"), "utf8");

  const wikis = await fetchWikis(project.projectKey);
  console.log(`[backlog] ${wikis.length}件のWikiを取得しました。`);

  const wikiRows = [];
  for (const wiki of wikis) {
    const detail = await apiGet(`/wikis/${wiki.id}`);
    const fileName = `${safeFileName(`${detail.id}-${detail.name}`)}.md`;
    await writeFile(path.join(WIKI_DIR, fileName), renderWikiMarkdown(detail), "utf8");
    wikiRows.push(`- [${safeText(detail.name)}](./wiki/${fileName})`);
  }

  await writeFile(path.join(OUT_DIR, "wikis.md"), [`# Backlog Wiki`, "", ...wikiRows, ""].join("\n"), "utf8");

  await writeFile(
    path.join(OUT_DIR, "README.md"),
    [
      "# Backlog Sync",
      "",
      `Project: ${project.projectKey}`,
      `Synced at: ${new Date().toISOString()}`,
      "",
      "- [Issues](./issues.md)",
      "- [Wiki](./wikis.md)",
      "- [Current task](./current-task.md)",
      "",
      "Generated by `npm run backlog:sync`.",
      "",
    ].join("\n"),
    "utf8",
  );

  console.log("[backlog] docs/backlog 配下への同期が完了しました。");
}

async function writeCurrentTask(issueKey) {
  await ensureOutputDirs();
  const issue = await apiGet(`/issues/${encodeURIComponent(issueKey)}`);
  const comments = await fetchComments(issue.issueKey);
  const markdown = renderIssueMarkdown(issue, comments, { currentTask: true });

  await writeFile(path.join(OUT_DIR, "current-task.md"), markdown, "utf8");
  await writeFile(path.join(ISSUES_DIR, `${safeFileName(issue.issueKey)}.md`), markdown, "utf8");

  console.log(`[backlog] ${issue.issueKey} を docs/backlog/current-task.md に出力しました。`);
}

async function fetchIssues(projectId) {
  const all = [];
  const count = 100;

  for (let offset = 0; all.length < config.maxIssues; offset += count) {
    const page = await apiGet("/issues", {
      "projectId[]": projectId,
      count: Math.min(count, config.maxIssues - all.length),
      offset,
      sort: "updated",
      order: "desc",
    });

    all.push(...page);
    if (page.length < count) break;
  }

  return all;
}

async function fetchComments(issueKey) {
  return apiGet(`/issues/${encodeURIComponent(issueKey)}/comments`, {
    count: 100,
    order: "asc",
  });
}

async function fetchWikis(projectIdOrKey) {
  return apiGet("/wikis", { projectIdOrKey });
}

async function apiGet(endpoint, params = {}) {
  const url = new URL(`${baseUrl}${endpoint}`);
  url.searchParams.set("apiKey", config.apiKey);

  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      url.searchParams.append(key, String(value));
    }
  }

  const safePath = `${endpoint}${Object.keys(params).length ? ` ${JSON.stringify(params)}` : ""}`;

  try {
    const response = await fetch(url);
    const text = await response.text();

    if (!response.ok) {
      throw new Error(`HTTP ${response.status} ${response.statusText}: ${truncate(sanitizeSecrets(text), 500)}`);
    }

    return text ? JSON.parse(text) : null;
  } catch (error) {
    throw new Error(`[backlog] API request failed: ${safePath}\n${error.message}`);
  }
}

function renderIssueMarkdown(issue, comments, options = {}) {
  const description = safeText(issue.description || "");
  const completionCriteria = extractCompletionCriteria(description);
  const title = options.currentTask ? "Current Backlog Task" : issue.issueKey;

  return [
    `# ${title}: ${safeText(issue.summary)}`,
    "",
    "## Summary",
    "",
    `- Issue Key: ${issue.issueKey}`,
    `- Title: ${safeText(issue.summary)}`,
    `- Status: ${safeText(issue.status?.name || "未設定")}`,
    `- Priority: ${safeText(issue.priority?.name || "未設定")}`,
    `- Assignee: ${renderUser(issue.assignee)}`,
    `- Updated: ${issue.updated || "未設定"}`,
    "",
    "## Description",
    "",
    description || "_No description._",
    "",
    "## Completion Criteria",
    "",
    completionCriteria || "_Backlogの説明から完了条件を検出できませんでした。必要に応じて追記してください。_",
    "",
    "## Comments",
    "",
    renderComments(comments),
    "",
  ].join("\n");
}

function renderWikiMarkdown(wiki) {
  return [
    `# ${safeText(wiki.name)}`,
    "",
    `- Wiki ID: ${wiki.id}`,
    `- Updated: ${wiki.updated || "未設定"}`,
    "",
    safeText(wiki.content || ""),
    "",
  ].join("\n");
}

function renderComments(comments) {
  if (!comments?.length) return "_No comments._";

  return comments
    .map((comment, index) => {
      const number = index + 1;
      const author = renderUser(comment.createdUser);
      const created = comment.created || "日時未設定";
      const content = safeText(comment.content || "");
      return [`### Comment ${number}`, "", `- Author: ${author}`, `- Created: ${created}`, "", content || "_No content._"].join("\n");
    })
    .join("\n\n");
}

function extractCompletionCriteria(description) {
  const lines = description.split(/\r?\n/);
  const headingPattern = /^(#{1,6}\s*)?(完了条件|受け入れ条件|受入条件|終了条件|acceptance criteria|definition of done|done)\s*:?\s*$/i;
  const nextHeadingPattern = /^(#{1,6}\s+|[^\n]{1,40}\s*:)\S/;
  const start = lines.findIndex((line) => headingPattern.test(line.trim()));

  if (start === -1) return "";

  const block = [];
  for (const line of lines.slice(start + 1)) {
    if (block.length > 0 && nextHeadingPattern.test(line.trim())) break;
    block.push(line);
  }

  return block.join("\n").trim();
}

function renderUser(user) {
  if (!user) return "未設定";
  if (config.redactPersonalInfo) return "REDACTED";
  return safeText(user.name || user.userId || "未設定");
}

function safeText(value) {
  const text = String(value ?? "");
  const withoutSecrets = sanitizeSecrets(text);
  if (!config.redactPersonalInfo) return withoutSecrets;

  return withoutSecrets
    .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "REDACTED_EMAIL")
    .replace(/@\w[\w.-]*/g, "REDACTED_MENTION")
    .replace(/\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{3,4}\b/g, "REDACTED_PHONE");
}

function sanitizeSecrets(value) {
  return String(value ?? "").replaceAll(config.apiKey, "REDACTED_API_KEY");
}

function safeFileName(value) {
  return String(value)
    .replace(/[\\/:*?"<>|]/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 120);
}

function truncate(value, maxLength) {
  return value.length > maxLength ? `${value.slice(0, maxLength)}...` : value;
}

async function ensureOutputDirs() {
  await mkdir(ISSUES_DIR, { recursive: true });
  await mkdir(WIKI_DIR, { recursive: true });
}

function requiredEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} が未設定です。.env を確認してください。`);
  }
  return value;
}

async function loadEnv() {
  try {
    const dotenv = await import("dotenv");
    dotenv.config();
  } catch {
    await loadEnvFallback();
    console.warn("[backlog] dotenv が見つからないため、簡易 .env 読み込みにフォールバックしました。npm install を実行してください。");
  }
}

async function loadEnvFallback() {
  const envPath = path.join(ROOT_DIR, ".env");
  if (!existsSync(envPath)) return;

  const content = await readFile(envPath, "utf8");
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const match = trimmed.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/i);
    if (!match) continue;

    const [, key, rawValue] = match;
    const value = rawValue.replace(/^['"]|['"]$/g, "");
    if (!process.env[key]) process.env[key] = value;
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
