import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const sourcesPath = path.join(__dirname, "news-sources.json");
const outputPath = path.join(rootDir, "news-data.js");
const maxItems = Number.parseInt(process.argv.find((arg) => arg.startsWith("--limit="))?.split("=")[1] || "5", 10);

const positiveWords = [
  "公開",
  "開催",
  "誕生",
  "デビュー",
  "オープン",
  "開始",
  "成功",
  "開発",
  "展示",
  "募集",
  "体験",
  "イベント",
  "発見",
  "受賞",
  "決定",
  "リニューアル",
  "解明",
  "誕生",
  "赤ちゃん",
  "新エリア",
];

const negativeWords = [
  "訃報",
  "事故",
  "中止",
  "休止",
  "休館",
  "値上げ",
  "お詫び",
  "障害",
  "不具合",
  "注意",
  "緊急",
  "災害",
  "感染",
  "台風",
  "接近",
  "営業について",
  "営業時間",
  "休業",
  "臨時",
];

async function main() {
  const sources = JSON.parse(await fs.readFile(sourcesPath, "utf8"));
  const fetched = [];

  for (const source of sources) {
    try {
      const items = await fetchSource(source);
      fetched.push(...items);
      console.log(`${source.name}: ${items.length}件`);
    } catch (error) {
      console.warn(`${source.name}: 取得失敗 - ${error.message}`);
    }
  }

  const selected = dedupeByUrl(fetched)
    .filter((item) => scoreItem(item) >= 2)
    .sort((a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0))
    .slice(0, maxItems)
    .map(toMorningCalmArticle);

  const articles = selected.length >= maxItems ? selected : [...selected, ...fallbackArticles()].slice(0, maxItems);
  const generatedAt = new Date().toISOString();
  const js = `// Generated by npm run news:fetch at ${generatedAt}
window.MORNING_CALM_NEWS = ${JSON.stringify(articles, null, 2)};
`;

  await fs.writeFile(outputPath, js, "utf8");
  console.log(`news-data.js を${articles.length}件で更新しました。`);
}

async function fetchSource(source) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  const response = await fetch(source.url, {
    signal: controller.signal,
    headers: {
      "user-agent": "MorningCalmPrototype/0.1 (+https://example.local)",
      accept: source.type === "rss" ? "application/rss+xml, application/atom+xml, text/xml, */*" : "text/html, */*",
    },
  }).finally(() => clearTimeout(timeout));

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }

  const buffer = await response.arrayBuffer();
  const contentType = response.headers.get("content-type") || "";
  const text = decodeResponse(buffer, contentType);
  if (source.type === "mediawiki") {
    return parseMediaWiki(text, source);
  }
  if (source.type === "rss" || looksLikeFeed(text)) {
    return parseFeed(text, source);
  }

  return parseHtmlList(text, source);
}

function parseFeed(xml, source) {
  const itemBlocks = matchAllBlocks(xml, "item");
  const entryBlocks = matchAllBlocks(xml, "entry");
  const blocks = itemBlocks.length > 0 ? itemBlocks : entryBlocks;

  return blocks.slice(0, 12).map((block) => {
    const title = cleanText(readTag(block, "title"));
    const link = readTag(block, "link") || readLinkHref(block) || source.url;
    const publishedAt = readTag(block, "pubDate") || readTag(block, "published") || readTag(block, "updated");
    return normalizeItem({ title, url: absolutize(link, source.url), publishedAt, source });
  }).filter(Boolean);
}

function parseHtmlList(html, source) {
  const withoutScripts = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "");
  const anchors = [...withoutScripts.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)];
  const items = [];

  for (const match of anchors) {
    const url = absolutize(match[1], source.url);
    const inner = match[2];
    const text = cleanText(inner);
    if (!isUsefulTitle(text, source)) continue;

    const nearbyStart = Math.max(0, match.index - 260);
    const nearbyEnd = Math.min(withoutScripts.length, match.index + inner.length + 260);
    const nearby = cleanText(withoutScripts.slice(nearbyStart, nearbyEnd));
    const publishedAt = extractDate(nearby);

    items.push(normalizeItem({ title: text, url, publishedAt, source }));
  }

  return items.filter(Boolean).slice(0, 20);
}

function parseMediaWiki(text, source) {
  const data = JSON.parse(text);
  const pages = Object.values(data.query?.pages || {});
  return pages
    .filter((page) => page.title && page.fullurl)
    .map((page) =>
      normalizeItem({
        title: page.title,
        url: page.fullurl,
        publishedAt: page.touched || "",
        source,
      }),
    )
    .filter(Boolean)
    .slice(0, 20);
}

function normalizeItem({ title, url, publishedAt, source }) {
  if (!title || !url) return null;
  return {
    title: title.slice(0, 80),
    url,
    publishedAt: normalizeDate(publishedAt),
    sourceName: source.name,
    category: source.category,
    visual: source.visual,
    licenseName: source.licenseName || "公式発表",
    licenseUrl: source.licenseUrl || "",
    attribution: source.attribution || source.name,
  };
}

function toMorningCalmArticle(item) {
  const factTitle = item.title.replace(/\s+/g, " ").trim();
  const category = item.category || inferCategory(factTitle);
  const body = writeOriginalColumn(item, category);

  return {
    category,
    title: rewriteTitle(factTitle, category),
    source: item.sourceName,
    sourceUrl: item.url,
    publishedAt: item.publishedAt,
    pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
    visual: item.visual || visualForCategory(category),
    licenseName: item.licenseName,
    licenseUrl: item.licenseUrl,
    attribution: item.attribution,
    body,
    hint: writeHint(category),
    facts: [
      `発表元: ${item.sourceName}`,
      `発表日: ${formatFactDate(item.publishedAt)}`,
      `公式タイトル: ${factTitle}`,
      `ライセンス/扱い: ${item.licenseName}`,
      `帰属: ${item.attribution}`,
    ],
  };
}

function writeOriginalColumn(item, category) {
  const source = item.sourceName;
  const title = item.title;

  if (category === "生きもの") {
    return `${source}から、${softenTitle(title)}という知らせが届いています。水辺や生きものの小さな変化を知る時間は、朝の気持ちを少し穏やかにしてくれます。`;
  }

  if (category === "研究") {
    return `${source}が、${softenTitle(title)}と発表しました。静かな研究の積み重ねが、未来の選択肢を少しずつ広げていることを感じられるニュースです。`;
  }

  if (category === "社会") {
    return `${source}から、${softenTitle(title)}という発表がありました。暮らしの仕組みが少し整っていく知らせは、今日を前向きに始める手がかりになります。`;
  }

  if (category === "世界") {
    return `${source}に、${softenTitle(title)}という知らせが掲載されています。遠くの出来事にも、前へ進む人や場所の気配を見つけられることがあります。`;
  }

  return `${source}から、${softenTitle(title)}という知らせが届いています。日々の近くにある小さな前進を、静かに受け取れるニュースです。`;
}

function rewriteTitle(title, category) {
  if (category === "生きもの") return `水辺から届いた新しい知らせ`;
  if (category === "研究") return `研究の積み重ねが一歩前へ`;
  if (category === "社会") return `暮らしを支える取り組みが進む`;
  if (category === "世界") return `世界から届いた前向きな知らせ`;
  return title.length <= 24 ? title : `${title.slice(0, 23)}...`;
}

function writeHint(category) {
  if (category === "生きもの") return "身近な生きものの変化に目を向けると、今日の景色が少しやわらぎます。";
  if (category === "研究") return "見えない場所の積み重ねが、毎日を支えているのかもしれません。";
  if (category === "社会") return "小さな改善をひとつ見つけて、今日の安心材料にしてみましょう。";
  if (category === "世界") return "遠くの前進をひとつ受け取り、自分の一日にも静かに重ねてみましょう。";
  return "新しい知らせをひとつだけ、静かに持って出かけてみましょう。";
}

function softenTitle(title) {
  return title
    .replace(/[「」『』]/g, "")
    .replace(/\s+/g, " ")
    .replace(/のお知らせ$/, "")
    .trim();
}

function inferCategory(title) {
  if (/水族館|動物|ペンギン|イルカ|魚|展示|生きもの|いきもの/.test(title)) return "生きもの";
  if (/研究|開発|発見|技術|大学|実験|成果/.test(title)) return "研究";
  return "社会";
}

function visualForCategory(category) {
  if (category === "生きもの") return "water";
  if (category === "研究") return "market";
  if (category === "社会") return "station";
  return "flowers";
}

function scoreItem(item) {
  const title = item.title || "";
  let score = 0;
  for (const word of positiveWords) if (title.includes(word)) score += 2;
  for (const word of negativeWords) if (title.includes(word)) score -= 4;
  if (item.publishedAt) score += 1;
  if (/採用|入札|メンテナンス|営業時間|料金|チケット|ショップ|レストラン|営業について|休館|休業/.test(title)) {
    score -= 3;
  }
  return score;
}

function dedupeByUrl(items) {
  const seen = new Set();
  return items.filter((item) => {
    if (!item?.url || seen.has(item.url)) return false;
    seen.add(item.url);
    return true;
  });
}

function isUsefulTitle(text, source) {
  if (!text || text.length < 8 || text.length > 90) return false;
  if (/^(詳しくはこちら|more|read more|一覧|前へ|次へ)$/i.test(text)) return false;
  if (text === source.name) return false;
  return /[ぁ-んァ-ン一-龠]/.test(text);
}

function looksLikeFeed(text) {
  return /<(rss|feed)\b/i.test(text);
}

function matchAllBlocks(text, tag) {
  return [...text.matchAll(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, "gi"))].map((match) => match[1]);
}

function readTag(text, tag) {
  const match = text.match(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, "i"));
  return match ? decodeEntities(stripCdata(match[1])).trim() : "";
}

function readLinkHref(text) {
  const match = text.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*>/i);
  return match ? match[1] : "";
}

function cleanText(value) {
  return decodeEntities(
    stripTags(value)
      .replace(/\s+/g, " ")
      .trim(),
  );
}

function decodeResponse(buffer, contentType) {
  const declared = contentType.match(/charset=([^;]+)/i)?.[1]?.trim();
  if (declared) return new TextDecoder(normalizeCharset(declared)).decode(buffer);

  const utf8 = new TextDecoder("utf-8").decode(buffer);
  const metaCharset = utf8.match(/<meta[^>]+charset=["']?\s*([^"'\s/>]+)/i)?.[1]?.trim();
  if (metaCharset && normalizeCharset(metaCharset) !== "utf-8") {
    return new TextDecoder(normalizeCharset(metaCharset)).decode(buffer);
  }

  return utf8;
}

function normalizeCharset(value) {
  const charset = String(value || "utf-8").toLowerCase();
  if (charset === "shift-jis" || charset === "shift_jis" || charset === "sjis" || charset === "windows-31j") {
    return "shift_jis";
  }
  return charset;
}

function stripTags(value) {
  return String(value || "").replace(/<[^>]+>/g, " ");
}

function stripCdata(value) {
  return String(value || "").replace(/^<!\[CDATA\[/, "").replace(/\]\]>$/, "");
}

function decodeEntities(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)));
}

function absolutize(url, baseUrl) {
  try {
    return new URL(url, baseUrl).toString();
  } catch {
    return baseUrl;
  }
}

function extractDate(text) {
  const match = text.match(/(20\d{2})[./年-]\s*(\d{1,2})[./月-]\s*(\d{1,2})/);
  if (!match) return "";
  const [, year, month, day] = match;
  return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

function normalizeDate(value) {
  if (!value) return "";
  const date = new Date(value);
  if (!Number.isNaN(date.getTime())) return date.toISOString();
  const extracted = extractDate(value);
  return extracted ? new Date(`${extracted}T00:00:00+09:00`).toISOString() : "";
}

function formatFactDate(value) {
  if (!value) return "未確認";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("ja-JP", { dateStyle: "medium" }).format(date);
}

function fallbackArticles() {
  const now = new Date().toISOString();
  return [
    {
      category: "生きもの",
      title: "水辺から届いた新しい知らせ",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "water",
      body:
        "水辺の施設から、新しい展示や生きものの成長に関する知らせが届いています。小さな変化を見守る時間は、朝の気持ちを少し穏やかにしてくれます。",
      hint: "身近な生きものの変化に目を向けると、今日の景色が少しやわらぎます。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
    {
      category: "研究",
      title: "研究の積み重ねが一歩前へ",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "market",
      body:
        "研究機関から、新しい成果に関する発表がありました。静かな積み重ねが未来の選択肢を広げていることを感じられるニュースです。",
      hint: "見えない場所の積み重ねが、毎日を支えているのかもしれません。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
    {
      category: "社会",
      title: "暮らしを支える取り組みが進む",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "station",
      body:
        "地域や公共機関から、暮らしを支える取り組みの発表がありました。毎日の土台が少し整う知らせは、静かな安心につながります。",
      hint: "小さな改善をひとつ見つけて、今日の安心材料にしてみましょう。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
    {
      category: "くらし",
      title: "新しい場所がひらく",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "flowers",
      body:
        "身近な場所で、新しい催しや展示が始まります。少し立ち寄れる選択肢が増えることは、日々の余白をつくる小さなニュースです。",
      hint: "今日は、いつもの場所にある小さな変化を探してみてもよさそうです。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
    {
      category: "学び",
      title: "親子で学べる催しが開催へ",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "breakfast",
      body:
        "公式発表で、親子向けの学びの催しが案内されています。新しいことを知る時間は、週末を少し明るくしてくれます。",
      hint: "気になる催しをひとつだけメモしておくと、楽しみが先に生まれます。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
  ];
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
