import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const sourcesPath = path.join(__dirname, "news-sources.json");
const dataDir = path.join(rootDir, "data");
const jsonOutputPath = path.join(dataDir, "news-items.json");
const jsOutputPath = path.join(rootDir, "news-data.js");

const options = parseArgs(process.argv.slice(2));
const maxItems = options.limit ?? 5;
const detailLimit = options.detailLimit ?? 12;
const timeoutMs = options.timeoutMs ?? 10000;

const positiveWords = [
  "公開",
  "開催",
  "誕生",
  "デビュー",
  "オープン",
  "開始",
  "成功",
  "開発",
  "展示",
  "募集",
  "体験",
  "イベント",
  "発見",
  "受賞",
  "決定",
  "リニューアル",
  "解明",
  "赤ちゃん",
  "新エリア",
  "初公開",
  "誕生",
];

const negativeWords = [
  "訃報",
  "事故",
  "中止",
  "休止",
  "休館",
  "休業",
  "値上げ",
  "お詫び",
  "障害",
  "不具合",
  "注意",
  "緊急",
  "災害",
  "感染",
  "台風",
  "接近",
  "営業について",
  "営業時間",
  "臨時",
];

async function main() {
  const sources = JSON.parse(await fs.readFile(sourcesPath, "utf8")).filter((source) => source.enabled !== false);
  const fetched = [];
  const failures = [];

  for (const source of sources) {
    try {
      const items = await fetchSource(source);
      fetched.push(...items);
      console.log(`${source.name}: ${items.length}件`);
    } catch (error) {
      failures.push({ source: source.name, error: error.message });
      console.warn(`${source.name}: 取得失敗 - ${error.message}`);
    }
  }

  const candidates = dedupeByUrl(fetched)
    .map((item) => ({ ...item, score: scoreItem(item) }))
    .filter((item) => item.score >= 2)
    .sort((a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0))
    .slice(0, detailLimit);

  const enriched = [];
  for (const item of candidates) {
    enriched.push(await enrichFromDetailPage(item).catch(() => item));
  }

  const selected = enriched.slice(0, maxItems).map(toMorningCalmArticle);
  const articles = selected.length >= maxItems ? selected : [...selected, ...fallbackArticles()].slice(0, maxItems);
  const generatedAt = new Date().toISOString();

  await fs.mkdir(dataDir, { recursive: true });
  await fs.writeFile(
    jsonOutputPath,
    `${JSON.stringify({ generatedAt, count: articles.length, failures, articles }, null, 2)}\n`,
    "utf8",
  );
  await fs.writeFile(
    jsOutputPath,
    `// Generated by npm run news:fetch at ${generatedAt}\nwindow.MORNING_CALM_NEWS = ${JSON.stringify(articles, null, 2)};\n`,
    "utf8",
  );

  console.log(`data/news-items.json と news-data.js を${articles.length}件で更新しました。`);
}

async function fetchSource(source) {
  const text = await fetchText(source.url, source);
  if (source.type === "mediawiki") return parseMediaWiki(text, source);
  if (source.type === "rss" || looksLikeFeed(text)) return parseFeed(text, source);
  return parseHtmlList(text, source);
}

async function enrichFromDetailPage(item) {
  const text = await fetchText(item.url, { type: "html" });
  const imageUrl = extractMetaContent(text, ["og:image", "twitter:image"]);
  const metaTitle = extractMetaContent(text, ["og:title", "twitter:title"]);
  const publishedAt =
    extractMetaContent(text, ["article:published_time", "date", "dc.date"]) ||
    extractDate(cleanText(text)) ||
    item.publishedAt;

  return {
    ...item,
    title: metaTitle ? cleanTitle(metaTitle) : item.title,
    publishedAt: normalizeDate(publishedAt),
    imageUrl: imageUrl ? absolutize(imageUrl, item.url) : item.imageUrl,
  };
}

async function fetchText(url, source) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        "user-agent": "MorningCalmPrototype/0.1",
        accept:
          source.type === "rss"
            ? "application/rss+xml, application/atom+xml, text/xml, */*"
            : "text/html, application/json, */*",
      },
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const buffer = await response.arrayBuffer();
    return decodeResponse(buffer, response.headers.get("content-type") || "");
  } finally {
    clearTimeout(timeout);
  }
}

function parseFeed(xml, source) {
  const itemBlocks = matchAllBlocks(xml, "item");
  const entryBlocks = matchAllBlocks(xml, "entry");
  const blocks = itemBlocks.length > 0 ? itemBlocks : entryBlocks;

  return blocks
    .slice(0, 20)
    .map((block) => {
      const title = cleanTitle(readTag(block, "title"));
      const link = readTag(block, "link") || readLinkHref(block) || source.url;
      const publishedAt = readTag(block, "pubDate") || readTag(block, "published") || readTag(block, "updated");
      return normalizeItem({ title, url: absolutize(link, source.url), publishedAt, source });
    })
    .filter(Boolean);
}

function parseHtmlList(html, source) {
  const withoutScripts = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "");
  const anchors = [...withoutScripts.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)];
  const items = [];

  for (const match of anchors) {
    const url = absolutize(match[1], source.url);
    const title = cleanTitle(match[2]);
    if (!isUsefulTitle(title, source)) continue;

    const nearbyStart = Math.max(0, match.index - 320);
    const nearbyEnd = Math.min(withoutScripts.length, match.index + match[2].length + 320);
    const nearby = cleanText(withoutScripts.slice(nearbyStart, nearbyEnd));
    const publishedAt = extractDate(nearby);

    items.push(normalizeItem({ title, url, publishedAt, source }));
  }

  return items.filter(Boolean).slice(0, 30);
}

function parseMediaWiki(text, source) {
  const data = JSON.parse(text);
  return Object.values(data.query?.pages || {})
    .filter((page) => page.title && page.fullurl)
    .map((page) =>
      normalizeItem({
        title: page.title,
        url: page.fullurl,
        publishedAt: page.touched || "",
        source,
      }),
    )
    .filter(Boolean)
    .slice(0, 20);
}

function normalizeItem({ title, url, publishedAt, source }) {
  if (!title || !url) return null;
  return {
    id: stableId(url),
    title: title.slice(0, 100),
    sourceUrl: url,
    url,
    publishedAt: normalizeDate(publishedAt),
    sourceName: source.name,
    category: source.category,
    visual: source.visual,
    imageUrl: "",
    licenseName: source.licenseName || "公式発表",
    licenseUrl: source.licenseUrl || "",
    attribution: source.attribution || source.name,
  };
}

function toMorningCalmArticle(item) {
  const factTitle = item.title.replace(/\s+/g, " ").trim();
  const category = item.category || inferCategory(factTitle);

  return {
    id: item.id,
    category,
    title: rewriteTitle(factTitle, category),
    originalTitle: factTitle,
    body: writeOriginalColumn(item, category),
    imageUrl: item.imageUrl || "",
    source: item.sourceName,
    sourceUrl: item.url,
    publishedAt: item.publishedAt,
    pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
    visual: item.visual || visualForCategory(category),
    licenseName: item.licenseName,
    licenseUrl: item.licenseUrl,
    attribution: item.attribution,
    hint: writeHint(category),
    facts: [
      `発表元: ${item.sourceName}`,
      `発表日: ${formatFactDate(item.publishedAt)}`,
      `公式タイトル: ${factTitle}`,
      `画像URL: ${item.imageUrl || "未取得"}`,
      `ライセンス/扱い: ${item.licenseName}`,
      `帰属: ${item.attribution}`,
    ],
  };
}

function writeOriginalColumn(item, category) {
  const source = item.sourceName;
  const title = softenTitle(item.title);

  if (category === "creatures") {
    return `${source}から、${title}という知らせが届いています。水辺や生きものの小さな変化を知る時間は、朝の気持ちを少し穏やかにしてくれます。`;
  }
  if (category === "research") {
    return `${source}が、${title}と発表しました。静かな研究の積み重ねが、未来の選択肢を少しずつ広げていることを感じられるニュースです。`;
  }
  if (category === "society") {
    return `${source}から、${title}という発表がありました。暮らしの仕組みが少し整っていく知らせは、今日を前向きに始める手がかりになります。`;
  }
  if (category === "world") {
    return `${source}に、${title}という知らせが掲載されています。遠くの出来事にも、前へ進む人や場所の気配を見つけられることがあります。`;
  }
  return `${source}から、${title}という知らせが届いています。日々の近くにある小さな前進を、静かに受け取れるニュースです。`;
}

function rewriteTitle(title, category) {
  if (category === "creatures") return "水辺から届いた新しい知らせ";
  if (category === "research") return "研究の積み重ねが一歩前へ";
  if (category === "society") return "暮らしを支える取り組みが進む";
  if (category === "world") return "世界から届いた前向きな知らせ";
  return title.length <= 24 ? title : `${title.slice(0, 23)}...`;
}

function writeHint(category) {
  if (category === "creatures") return "身近な生きものの変化に目を向けると、今日の景色が少しやわらぎます。";
  if (category === "research") return "見えない場所の積み重ねが、毎日を支えているのかもしれません。";
  if (category === "society") return "小さな改善をひとつ見つけて、今日の安心材料にしてみましょう。";
  if (category === "world") return "遠くの前進をひとつ受け取り、自分の一日にも静かに重ねてみましょう。";
  return "新しい知らせをひとつだけ、静かに持って出かけてみましょう。";
}

function scoreItem(item) {
  const title = item.title || "";
  let score = 0;
  for (const word of positiveWords) if (title.includes(word)) score += 2;
  for (const word of negativeWords) if (title.includes(word)) score -= 4;
  if (item.publishedAt) score += 1;
  if (/採用|入札|メンテナンス|営業時間|料金|チケット|ショップ|レストラン|営業について|休館|休業/.test(title)) {
    score -= 3;
  }
  return score;
}

function inferCategory(title) {
  if (/水族館|動物|ペンギン|イルカ|魚|展示|生きもの|いきもの/.test(title)) return "creatures";
  if (/研究|開発|発見|技術|大学|実験|成果|解明/.test(title)) return "research";
  return "society";
}

function visualForCategory(category) {
  if (category === "creatures") return "water";
  if (category === "research") return "market";
  if (category === "society") return "station";
  return "flowers";
}

function dedupeByUrl(items) {
  const seen = new Set();
  return items.filter((item) => {
    if (!item?.url || seen.has(item.url)) return false;
    seen.add(item.url);
    return true;
  });
}

function isUsefulTitle(text, source) {
  if (!text || text.length < 8 || text.length > 100) return false;
  if (/^(詳しくはこちら|more|read more|一覧|前へ|次へ)$/i.test(text)) return false;
  if (text === source.name) return false;
  return /[ぁ-んァ-ン一-龠A-Za-z]/.test(text);
}

function extractMetaContent(html, properties) {
  for (const property of properties) {
    const escaped = property.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const patterns = [
      new RegExp(`<meta\\b[^>]*(?:property|name)=["']${escaped}["'][^>]*content=["']([^"']+)["'][^>]*>`, "i"),
      new RegExp(`<meta\\b[^>]*content=["']([^"']+)["'][^>]*(?:property|name)=["']${escaped}["'][^>]*>`, "i"),
    ];
    for (const pattern of patterns) {
      const match = html.match(pattern);
      if (match?.[1]) return decodeEntities(match[1]).trim();
    }
  }
  return "";
}

function cleanTitle(value) {
  return cleanText(value)
    .replace(/\s+/g, " ")
    .replace(/\s*[|｜].*$/, "")
    .trim();
}

function softenTitle(title) {
  return title
    .replace(/[「」『』]/g, "")
    .replace(/\s+/g, " ")
    .replace(/のお知らせ$/, "")
    .trim();
}

function looksLikeFeed(text) {
  return /<(rss|feed)\b/i.test(text);
}

function matchAllBlocks(text, tag) {
  return [...text.matchAll(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, "gi"))].map((match) => match[1]);
}

function readTag(text, tag) {
  const match = text.match(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, "i"));
  return match ? decodeEntities(stripCdata(match[1])).trim() : "";
}

function readLinkHref(text) {
  const match = text.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*>/i);
  return match ? match[1] : "";
}

function cleanText(value) {
  return decodeEntities(stripTags(value).replace(/\s+/g, " ").trim());
}

function decodeResponse(buffer, contentType) {
  const declared = contentType.match(/charset=([^;]+)/i)?.[1]?.trim();
  if (declared) return new TextDecoder(normalizeCharset(declared)).decode(buffer);

  const utf8 = new TextDecoder("utf-8").decode(buffer);
  const metaCharset = utf8.match(/<meta[^>]+charset=["']?\s*([^"'\s/>]+)/i)?.[1]?.trim();
  if (metaCharset && normalizeCharset(metaCharset) !== "utf-8") {
    return new TextDecoder(normalizeCharset(metaCharset)).decode(buffer);
  }

  return utf8;
}

function normalizeCharset(value) {
  const charset = String(value || "utf-8").toLowerCase();
  if (["shift-jis", "shift_jis", "sjis", "windows-31j"].includes(charset)) return "shift_jis";
  return charset;
}

function stripTags(value) {
  return String(value || "").replace(/<[^>]+>/g, " ");
}

function stripCdata(value) {
  return String(value || "").replace(/^<!\[CDATA\[/, "").replace(/\]\]>$/, "");
}

function decodeEntities(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)));
}

function absolutize(url, baseUrl) {
  try {
    return new URL(url, baseUrl).toString();
  } catch {
    return baseUrl;
  }
}

function extractDate(text) {
  const match = text.match(/(20\d{2})[./年-]\s*(\d{1,2})[./月-]\s*(\d{1,2})/);
  if (!match) return "";
  const [, year, month, day] = match;
  return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

function normalizeDate(value) {
  if (!value) return "";
  const date = new Date(value);
  if (!Number.isNaN(date.getTime())) return date.toISOString();
  const extracted = extractDate(value);
  return extracted ? new Date(`${extracted}T00:00:00+09:00`).toISOString() : "";
}

function formatFactDate(value) {
  if (!value) return "未確認";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("ja-JP", { dateStyle: "medium" }).format(date);
}

function stableId(value) {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash * 31 + value.charCodeAt(index)) >>> 0;
  }
  return `news-${hash.toString(16)}`;
}

function fallbackArticles() {
  const now = new Date().toISOString();
  return [
    {
      id: "fallback-water",
      category: "creatures",
      title: "水辺から届いた新しい知らせ",
      originalTitle: "取得件数不足時のデモ記事",
      body:
        "水辺の施設から、新しい展示や生きものの成長に関する知らせが届いています。小さな変化を見守る時間は、朝の気持ちを少し穏やかにしてくれます。",
      imageUrl: "",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "water",
      licenseName: "デモ",
      licenseUrl: "",
      attribution: "Morning Calm",
      hint: "身近な生きものの変化に目を向けると、今日の景色が少しやわらぎます。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
    {
      id: "fallback-research",
      category: "research",
      title: "研究の積み重ねが一歩前へ",
      originalTitle: "取得件数不足時のデモ記事",
      body:
        "研究機関から、新しい成果に関する発表がありました。静かな積み重ねが未来の選択肢を広げていることを感じられるニュースです。",
      imageUrl: "",
      source: "デモデータ",
      sourceUrl: "",
      publishedAt: now,
      pipeline: "公式発表のメタ情報から、本文を流用せずに新規作成",
      visual: "market",
      licenseName: "デモ",
      licenseUrl: "",
      attribution: "Morning Calm",
      hint: "見えない場所の積み重ねが、毎日を支えているのかもしれません。",
      facts: ["取得件数が不足したため、デモ記事を補完しました。"],
    },
  ];
}

function parseArgs(args) {
  const parsed = {};
  for (const arg of args) {
    const [key, value] = arg.replace(/^--/, "").split("=");
    if (key === "limit") parsed.limit = Number.parseInt(value, 10);
    if (key === "detail-limit") parsed.detailLimit = Number.parseInt(value, 10);
    if (key === "timeout-ms") parsed.timeoutMs = Number.parseInt(value, 10);
  }
  return parsed;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
